import type { CSSProperties } from "react";

export const gameScreenStyles = {
	container: {
		position: "relative",
		display: "flex",
		flexDirection: "column",
		width: "100%",
		height: "100%",
		background: "#1a1a1a",
		overflow: "hidden",
	},
	toolbar: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		height: 48,
		padding: "0 16px",
		background: "#242424",
		borderBottom: "1px solid #333",
		flexShrink: 0,
	},
	toolbarLeft: { display: "flex", alignItems: "center", gap: 16 },
	toolbarRight: { display: "flex", alignItems: "center", gap: 16 },
	towerLabel: {
		fontSize: 14,
		fontWeight: 600,
		color: "#ccc",
		maxWidth: 140,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		cursor: "pointer",
		background: "transparent",
		border: "none",
		borderBottom: "1px dashed #555",
		padding: 0,
	},
	renameForm: {
		display: "flex",
		alignItems: "center",
		gap: 4,
	},
	renameInput: {
		width: 120,
		padding: "3px 8px",
		borderRadius: 4,
		border: "1px solid #555",
		background: "#1a1a1a",
		color: "#e0e0e0",
		fontSize: 13,
		outline: "none",
	},
	renameSave: {
		padding: "3px 8px",
		borderRadius: 4,
		border: "1px solid #3a7bd5",
		background: "transparent",
		color: "#3a7bd5",
		fontSize: 11,
		cursor: "pointer",
	},
	renameCancel: {
		padding: "3px 8px",
		borderRadius: 4,
		border: "1px solid #555",
		background: "transparent",
		color: "#888",
		fontSize: 11,
		cursor: "pointer",
	},
	renameError: {
		fontSize: 11,
		color: "#f87171",
	},
	toolGroup: { display: "flex", gap: 4 },
	toolBtn: {
		padding: "4px 10px",
		borderRadius: 4,
		border: "1px solid",
		fontSize: 12,
		fontWeight: 500,
		cursor: "pointer",
		transition: "all 0.1s",
	},
	cashDisplay: {
		fontSize: 15,
		fontWeight: 700,
		color: "#4ade80",
		fontVariantNumeric: "tabular-nums",
	},
	statItem: { fontSize: 12, color: "#aaa" },
	leaveBtn: {
		padding: "4px 12px",
		borderRadius: 4,
		border: "1px solid #555",
		background: "transparent",
		color: "#aaa",
		fontSize: 12,
		cursor: "pointer",
	},
	canvasWrapper: { flex: 1, overflow: "hidden", position: "relative" },
	debugPanel: {
		position: "absolute",
		top: 12,
		right: 12,
		zIndex: 40,
		minWidth: 196,
		padding: "10px 12px",
		borderRadius: 8,
		background: "rgba(14, 18, 24, 0.9)",
		border: "1px solid rgba(123, 148, 170, 0.35)",
		backdropFilter: "blur(6px)",
		display: "flex",
		flexDirection: "column",
		gap: 4,
		pointerEvents: "auto",
	},
	debugTitle: {
		fontSize: 11,
		fontWeight: 700,
		color: "#d9e7f2",
		textTransform: "uppercase",
		letterSpacing: "0.08em",
		marginBottom: 2,
	},
	debugRow: {
		display: "flex",
		justifyContent: "space-between",
		gap: 12,
		fontSize: 12,
		color: "#aab8c2",
		fontVariantNumeric: "tabular-nums",
	},
	speedButtons: {
		display: "flex",
		gap: 4,
	},
	speedButton: {
		padding: "1px 6px",
		borderRadius: 3,
		border: "1px solid #555",
		background: "transparent",
		color: "#aab8c2",
		fontSize: 11,
		cursor: "pointer",
		lineHeight: "16px",
	},
	speedButtonActive: {
		background: "#3b82f6",
		borderColor: "#3b82f6",
		color: "#fff",
	},
	statusBar: {
		display: "flex",
		alignItems: "center",
		height: 28,
		padding: "0 16px",
		background: "#1e1e1e",
		borderTop: "1px solid #2a2a2a",
		gap: 8,
		flexShrink: 0,
	},
	statusDot: { width: 7, height: 7, borderRadius: "50%", flexShrink: 0 },
	statusText: { fontSize: 11, color: "#888" },
	reconnectBtn: {
		padding: "2px 8px",
		borderRadius: 3,
		border: "1px solid #555",
		background: "transparent",
		color: "#ccc",
		fontSize: 11,
		cursor: "pointer",
	},
	statusRight: { marginLeft: "auto", fontSize: 11, color: "#666" },
	towerIdSmall: { fontFamily: "monospace", color: "#888" },
	toastContainer: {
		position: "absolute",
		bottom: 40,
		right: 16,
		display: "flex",
		flexDirection: "column",
		alignItems: "flex-end",
		gap: 6,
		pointerEvents: "none",
		zIndex: 100,
	},
	toastError: {
		padding: "7px 14px",
		borderRadius: 6,
		background: "#3a1a1a",
		border: "1px solid #c0392b",
		color: "#f87171",
		fontSize: 13,
		whiteSpace: "nowrap",
	},
	toastInfo: {
		padding: "7px 14px",
		borderRadius: 6,
		background: "#1a2a3a",
		border: "1px solid #3a7bd5",
		color: "#93c5fd",
		fontSize: 13,
		whiteSpace: "nowrap",
	},
	modalOverlay: {
		position: "fixed",
		top: 0,
		left: 0,
		right: 0,
		bottom: 0,
		background: "rgba(0, 0, 0, 0.6)",
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		zIndex: 200,
	},
	modal: {
		background: "#242424",
		border: "1px solid #444",
		borderRadius: 12,
		padding: "24px 32px",
		minWidth: 340,
		maxWidth: 420,
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		gap: 12,
		boxShadow: "0 8px 32px rgba(0, 0, 0, 0.5)",
	},
	modalIcon: {
		fontSize: 36,
	},
	modalTitle: {
		fontSize: 18,
		fontWeight: 700,
		color: "#e0e0e0",
	},
	modalMessage: {
		fontSize: 14,
		color: "#aaa",
		textAlign: "center",
		lineHeight: "1.5",
	},
	modalButtons: {
		display: "flex",
		gap: 12,
		marginTop: 8,
	},
	modalAccept: {
		padding: "8px 20px",
		borderRadius: 6,
		border: "1px solid #4ade80",
		background: "rgba(74, 222, 128, 0.15)",
		color: "#4ade80",
		fontSize: 14,
		fontWeight: 600,
		cursor: "pointer",
	},
	modalDecline: {
		padding: "8px 20px",
		borderRadius: 6,
		border: "1px solid #555",
		background: "transparent",
		color: "#aaa",
		fontSize: 14,
		fontWeight: 600,
		cursor: "pointer",
	},
	inspectDialog: {
		background: "#242424",
		border: "1px solid #444",
		borderRadius: 12,
		padding: "16px 20px",
		minWidth: 280,
		maxWidth: 380,
		display: "flex",
		flexDirection: "column",
		gap: 12,
		boxShadow: "0 8px 32px rgba(0, 0, 0, 0.5)",
	},
	inspectHeader: {
		display: "flex",
		justifyContent: "space-between",
		alignItems: "center",
	},
	inspectTitle: {
		fontSize: 16,
		fontWeight: 700,
		color: "#e0e0e0",
	},
	inspectClose: {
		background: "transparent",
		border: "none",
		color: "#888",
		fontSize: 20,
		cursor: "pointer",
		padding: "0 4px",
		lineHeight: 1,
	},
	inspectSection: {
		display: "flex",
		flexDirection: "column",
		gap: 6,
	},
	inspectRow: {
		display: "flex",
		justifyContent: "space-between",
		alignItems: "center",
		fontSize: 13,
	},
	inspectLabel: {
		color: "#888",
		fontSize: 12,
		fontWeight: 600,
		textTransform: "uppercase",
		letterSpacing: "0.05em",
	},
	inspectValue: {
		color: "#ccc",
		fontSize: 13,
		fontVariantNumeric: "tabular-nums",
	},
	rentButtons: {
		display: "flex",
		gap: 4,
		marginTop: 4,
	},
	rentButton: {
		flex: 1,
		padding: "6px 8px",
		borderRadius: 4,
		border: "1px solid #555",
		background: "transparent",
		color: "#aaa",
		fontSize: 12,
		fontWeight: 500,
		cursor: "pointer",
	},
	rentButtonActive: {
		background: "rgba(74, 222, 128, 0.15)",
		borderColor: "#4ade80",
		color: "#4ade80",
	},
	carButtons: {
		display: "flex",
		gap: 8,
		marginTop: 4,
	},
	carButton: {
		flex: 1,
		padding: "6px 12px",
		borderRadius: 4,
		border: "1px solid #555",
		background: "transparent",
		color: "#ccc",
		fontSize: 12,
		fontWeight: 500,
		cursor: "pointer",
	},
	carButtonDisabled: {
		opacity: 0.4,
		cursor: "default",
	},
} as const satisfies Record<string, CSSProperties>;
