name = "tower-together-worker"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[rules]]
type = "Text"
globs = ["migrations/*.sql"]

[dev]
port = 8787

[[durable_objects.bindings]]
name = "TOWER_ROOM"
class_name = "TowerRoom"

[[durable_objects.bindings]]
name = "TOWER_REGISTRY"
class_name = "TowerRegistry"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TowerRoom"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["TowerRegistry"]
